/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-20 05:56:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class now_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/now.css\" rel=\"stylesheet\"/>   \r\n");
      out.write("\r\n");
      out.write("    <link rel=\"canonical\" href=\"https://getbootstrap.com/docs/5.3/examples/album/\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicons -->\r\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"/docs/5.3/assets/img/favicons/apple-touch-icon.png\" sizes=\"180x180\">\r\n");
      out.write("<link rel=\"icon\" href=\"/docs/5.3/assets/img/favicons/favicon-32x32.png\" sizes=\"32x32\" type=\"image/png\">\r\n");
      out.write("<link rel=\"icon\" href=\"/docs/5.3/assets/img/favicons/favicon-16x16.png\" sizes=\"16x16\" type=\"image/png\">\r\n");
      out.write("<link rel=\"manifest\" href=\"/docs/5.3/assets/img/favicons/manifest.json\">\r\n");
      out.write("<link rel=\"mask-icon\" href=\"/docs/5.3/assets/img/favicons/safari-pinned-tab.svg\" color=\"#712cf9\">\r\n");
      out.write("<link rel=\"icon\" href=\"/docs/5.3/assets/img/favicons/favicon.ico\">\r\n");
      out.write("<meta name=\"theme-color\" content=\"#712cf9\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<main>\r\n");
      out.write("\r\n");
      out.write("    <!-- 카테고리 -->\r\n");
      out.write("  <section class=\" text-center \" style=\"background-color: #fff2cc\">\r\n");
      out.write("    <div class=\"row py-lg-5\">\r\n");
      out.write("      <div class=\"col-lg-6 col-md-8 mx-auto\">\r\n");
      out.write("        <h1 class=\"fw-light\">Kategorie</h1>\r\n");
      out.write("        <p class=\"lead text-muted\"></p>\r\n");
      out.write("        <p>\r\n");
      out.write("          <a href=\"#\" class=\"btn btn-primary my-2\">스포츠/레저</a>\r\n");
      out.write("          <a href=\"#\" class=\"btn btn-primary my-2\">문화/예술</a>\r\n");
      out.write("          <a href=\"#\" class=\"btn btn-primary my-2\">교육/언어</a>\r\n");
      out.write("          <a href=\"#\" class=\"btn btn-primary my-2\">요리/음료</a>\r\n");
      out.write("          <a href=\"#\" class=\"btn btn-primary my-2\">헨드메이드</a>\r\n");
      out.write("          <a href=\"#\" class=\"btn btn-primary my-2\">기타</a>\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("   <!-- 카테고리end -->\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("    <!-- 검색창 -->\r\n");
      out.write("   <nav class=\"navbar bg-light\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("        <img src=\"../resources/imges/heder.png\" alt=\"Logo\" width=\"30\" height=\"24\" class=\"d-inline-block align-text-top\">\r\n");
      out.write("        \r\n");
      out.write("        </a>\r\n");
      out.write("      <form class=\"d-flex\" role=\"search\">\r\n");
      out.write("        <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("        <button class=\"btn btn-primary\" type=\"button\">Search</button>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <!-- 검색창 -->\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   <br>\r\n");
      out.write("\r\n");
      out.write("   <!-- 게시물 -->\r\n");
      out.write("   <!--인기 강습-->\r\n");
      out.write("   <div class=\"row popular\">\r\n");
      out.write("    <div class=\"container popular\">\r\n");
      out.write("      <div class=\"row p_row\">\r\n");
      out.write("      \r\n");
      out.write("        <div class=\"col-md-2\"></div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-md-8\">\r\n");
      out.write("        \r\n");
      out.write("          <!-- loacation: 나중에 이동할 상세페이지 넣을 것임 -->\r\n");
      out.write("          \r\n");
      out.write("          <div class = \"p_article\" onclick=\"location.href='http://google.com'\">\r\n");
      out.write("              <div class = \"p_class\"><a href =\"#\"><img src=\"../resources/imges/test.jpg\" alt=\"...\" class=\"p_img\"></a></div>\r\n");
      out.write("              <a href =\"#\"><p class = \"p_small\"><b>BNO</b></p></a>\r\n");
      out.write("              <a href =\"#\"><p class = \"p_small\"><b>TITEL</b></p></a>\r\n");
      out.write("              <a href =\"#\"><p class =\"p_price\"><i class=\"bi bi-basket2\">&nbsp</i><b>30,000원~</b></p></a>\r\n");
      out.write("              <a href =\"#\"><p class =\"p_star\"><i class=\"bi bi-star-fill\"></i>4.8</a> | 200개의 리뷰</p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class = \"p_article\" onclick=\"location.href='http://google.com'\">\r\n");
      out.write("              <div class = \"p_class\"><a href =\"#\"><img src=\"../resources/imges/test1.jpg\" alt=\"...\" class=\"p_img\"></a></div>\r\n");
      out.write("              <a href =\"#\"><p class = \"p_small\"><b>BNO</b></p></a>\r\n");
      out.write("              <a href =\"#\"><p class = \"p_small\"><b>TITEL</b></p></a>\r\n");
      out.write("              <a href =\"#\"><p class =\"p_price\"><i class=\"bi bi-basket2\">&nbsp</i><b>30,000원~</b></p></a>\r\n");
      out.write("              <a href =\"#\"><p class =\"p_star\"><i class=\"bi bi-star-fill\"></i>4.8</a> | 200개의 리뷰</p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class = \"p_article\" onclick=\"location.href='http://google.com'\">\r\n");
      out.write("              <div class = \"p_class\"><a href =\"#\"><img src=\"../resources/imges/test4.jpg\" alt=\"...\" class=\"p_img\"></a></div>\r\n");
      out.write("              <a href =\"#\"><p class = \"p_small\"><b>BNO</b></p></a>\r\n");
      out.write("              <a href =\"#\"><p class = \"p_small\"><b>TITEL</b></p></a>\r\n");
      out.write("              <a href =\"#\"><p class =\"p_price\"><i class=\"bi bi-basket2\">&nbsp</i><b>30,000원~</b></p></a>\r\n");
      out.write("              <a href =\"#\"><p class =\"p_star\"><i class=\"bi bi-star-fill\"></i>4.8</a> | 200개의 리뷰</p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div> \r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-2\"></div>\r\n");
      out.write("      \r\n");
      out.write("      </div> <!-- p_row end-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <div class=\"row p_row\">\r\n");
      out.write("      \r\n");
      out.write("        <div class=\"col-md-2\"></div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-md-8\">\r\n");
      out.write("        \r\n");
      out.write("          <!-- loacation: 나중에 이동할 상세페이지 넣을 것임 -->\r\n");
      out.write("          \r\n");
      out.write("          <div class = \"p_article\" onclick=\"location.href='http://google.com'\">\r\n");
      out.write("            <div class = \"p_class\"><a href =\"#\"><img src=\"../resources/imges/test.jpg\" alt=\"...\" class=\"p_img\"></a></div>\r\n");
      out.write("            <a href =\"#\"><p class = \"p_small\"><b>BNO</b></p></a>\r\n");
      out.write("            <a href =\"#\"><p class = \"p_small\"><b>TITEL</b></p></a>\r\n");
      out.write("            <a href =\"#\"><p class =\"p_price\"><i class=\"bi bi-basket2\">&nbsp</i><b>30,000원~</b></p></a>\r\n");
      out.write("            <a href =\"#\"><p class =\"p_star\"><i class=\"bi bi-star-fill\"></i>4.8</a> | 200개의 리뷰</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class = \"p_article\" onclick=\"location.href='http://google.com'\">\r\n");
      out.write("            <div class = \"p_class\"><a href =\"#\"><img src=\"../resources/imges/test1.jpg\" alt=\"...\" class=\"p_img\"></a></div>\r\n");
      out.write("            <a href =\"#\"><p class = \"p_small\"><b>BNO</b></p></a>\r\n");
      out.write("            <a href =\"#\"><p class = \"p_small\"><b>TITEL</b></p></a>\r\n");
      out.write("            <a href =\"#\"><p class =\"p_price\"><i class=\"bi bi-basket2\">&nbsp</i><b>30,000원~</b></p></a>\r\n");
      out.write("            <a href =\"#\"><p class =\"p_star\"><i class=\"bi bi-star-fill\"></i>4.8</a> | 200개의 리뷰</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class = \"p_article\" onclick=\"location.href='http://google.com'\">\r\n");
      out.write("            <div class = \"p_class\"><a href =\"#\"><img src=\"../resources/imges/test4.jpg\" alt=\"...\" class=\"p_img\"></a></div>\r\n");
      out.write("            <a href =\"#\"><p class = \"p_small\"><b>BNO</b></p></a>\r\n");
      out.write("            <a href =\"#\"><p class = \"p_small\"><b>TITEL</b></p></a>\r\n");
      out.write("            <a href =\"#\"><p class =\"p_price\"><i class=\"bi bi-basket2\">&nbsp</i><b>30,000원~</b></p></a>\r\n");
      out.write("            <a href =\"#\"><p class =\"p_star\"><i class=\"bi bi-star-fill\"></i>4.8</a> | 200개의 리뷰</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        </div> \r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-2\"></div>\r\n");
      out.write("      \r\n");
      out.write("      </div> <!-- p_row end-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <div class=\"row p_row\">\r\n");
      out.write("      \r\n");
      out.write("        <div class=\"col-md-2\"></div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-md-8\">\r\n");
      out.write("        \r\n");
      out.write("          <!-- loacation: 나중에 이동할 상세페이지 넣을 것임 -->\r\n");
      out.write("          \r\n");
      out.write("          <div class = \"p_article\" onclick=\"location.href='http://google.com'\">\r\n");
      out.write("            <div class = \"p_class\"><a href =\"#\"><img src=\"../resources/imges/test.jpg\" alt=\"...\" class=\"p_img\"></a></div>\r\n");
      out.write("            <a href =\"#\"><p class = \"p_small\"><b>BNO</b></p></a>\r\n");
      out.write("            <a href =\"#\"><p class = \"p_small\"><b>TITEL</b></p></a>\r\n");
      out.write("            <a href =\"#\"><p class =\"p_price\"><i class=\"bi bi-basket2\">&nbsp</i><b>30,000원~</b></p></a>\r\n");
      out.write("            <a href =\"#\"><p class =\"p_star\"><i class=\"bi bi-star-fill\"></i>4.8</a> | 200개의 리뷰</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class = \"p_article\" onclick=\"location.href='http://google.com'\">\r\n");
      out.write("            <div class = \"p_class\"><a href =\"#\"><img src=\"../resources/imges/test1.jpg\" alt=\"...\" class=\"p_img\"></a></div>\r\n");
      out.write("            <a href =\"#\"><p class = \"p_small\"><b>BNO</b></p></a>\r\n");
      out.write("            <a href =\"#\"><p class = \"p_small\"><b>TITEL</b></p></a>\r\n");
      out.write("            <a href =\"#\"><p class =\"p_price\"><i class=\"bi bi-basket2\">&nbsp</i><b>30,000원~</b></p></a>\r\n");
      out.write("            <a href =\"#\"><p class =\"p_star\"><i class=\"bi bi-star-fill\"></i>4.8</a> | 200개의 리뷰</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class = \"p_article\" onclick=\"location.href='http://google.com'\">\r\n");
      out.write("            <div class = \"p_class\"><a href =\"#\"><img src=\"../resources/imges/test4.jpg\" alt=\"...\" class=\"p_img\"></a></div>\r\n");
      out.write("            <a href =\"#\"><p class = \"p_small\"><b>BNO</b></p></a>\r\n");
      out.write("            <a href =\"#\"><p class = \"p_small\"><b>TITEL</b></p></a>\r\n");
      out.write("            <a href =\"#\"><p class =\"p_price\"><i class=\"bi bi-basket2\">&nbsp</i><b>30,000원~</b></p></a>\r\n");
      out.write("            <a href =\"#\"><p class =\"p_star\"><i class=\"bi bi-star-fill\"></i>4.8</a> | 200개의 리뷰</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        </div> \r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-2\"></div>\r\n");
      out.write("      \r\n");
      out.write("      </div> <!-- p_row end-->\r\n");
      out.write("\r\n");
      out.write("      <div class=\"row\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div><!--인기 강습 end-->\r\n");
      out.write("  <!-- 게시물end -->\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("<!-- 글쓰기 -->\r\n");
      out.write("\r\n");
      out.write("<br><br><br>\r\n");
      out.write("<div class=\"container text-anchor\">\r\n");
      out.write("   \r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-dark\">글쓰기</button>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("  </div>\r\n");
      out.write("  <br><br>\r\n");
      out.write("  <!-- 글쓰기end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- 페이징 -->\r\n");
      out.write("  <br><br><br>\r\n");
      out.write("  <nav aria-label=\"Page navigation example\">\r\n");
      out.write("    <ul class=\"pagination justify-content-center\">\r\n");
      out.write("      <li class=\"page-item disabled\">\r\n");
      out.write("        <a class=\"page-link\">Previous</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"page-item\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("      <li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("      <li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("      <li class=\"page-item\"><a class=\"page-link\" href=\"#\">4</a></li>\r\n");
      out.write("      <li class=\"page-item\"><a class=\"page-link\" href=\"#\">5</a></li>\r\n");
      out.write("      <li class=\"page-item\">\r\n");
      out.write("        <a class=\"page-link\" href=\"#\">Next</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <!-- 페이징end -->\r\n");
      out.write("\r\n");
      out.write("  <br><br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
